version: "3.8"

services:
  db:
    image: postgres:16
    container_name: furniture_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 381141
      POSTGRES_DB: furniture
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: furniture_redis
    restart: always
    environment:
      REDIS_PASSWORD: 1234
    ports:
      - "6379:6379"

volumes:
  pgdata:
